// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qakgwdqiaqlqudsuxzgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFha2d3ZHFpYXFscXVkc3V4emdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNDgyMjIsImV4cCI6MjA1ODkyNDIyMn0.l1R1BQHSouQCq3Km5ZWv91SUucuI-G89guzDu5mPfow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);